### ISSUE TITLE
Вопросы по проекту

### ISSUE THREAD

**Issue by AlexDeusov** [ZiGNicK/MyDragonHills#1]
* В требованиях к проекту указана возможность просмотра таблицы лидеров, предполагает ли это использование БД и означает ли невозможность работы приложения без подключения к Интернету?
* Для чего нужен внутриигровой магазин и означает ли покупка товаров в нем серьезные изменения баланса игры?
* Планируется ли возможность создания версий игры для iOS-устройств?

**Comment by ZiGNicK** [comment]
1) Да, но 90% что это будет реализовано через Google Leaderboards, и, как следствие, GPGames, на котором основаны лидерборды, требует подклчения к сети
2) В доке указано, что кристаллы будут помогать в последующих играх. За кристаллы можно будет купить зелья ускорения, огня и удвоения очков. Позже это будет грамотно оформлено и реализовано
3) На iOS не будет, т.к. нет мака

Большое спасибо за отзыв!
